# JANGAN SENTUH

services:

  student:
    build: ./student
    container_name: student-svc
    ports:
      - "8081:8081"
    depends_on:
      mysql-db:
        condition: service_healthy
    networks:
      - micronet
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://localhost:8081/api/students/health" ]
      interval: 10s
      timeout: 5s
      retries: 3

  enrollment:
    build: ./enrollment
    container_name: enrollment-svc
    ports:
      - "8082:8082"
    environment:
      # Use Docker service name for inter-service calls
      USER_SERVICE_URL: http://student:8081
    depends_on:
      mysql-db:
        condition: service_healthy
      rabbitmq-server:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://localhost:8082/api/enrollments/health" ]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - micronet

  notification:
    build: ./notification
    container_name: notification-svc
    ports:
      - "8083:8083"
    environment:
      # Use Docker service name for inter-service calls
      USER_SERVICE_URL: http://student:8081
    depends_on:
      mysql-db:
        condition: service_healthy
      rabbitmq-server:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://localhost:8083/api/notifications/health" ]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - micronet

  booking:
    build: ./booking
    container_name: booking-api-svc
    ports:
      - "8084:8084"
    depends_on:
      mysql-db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://localhost:8084/api/bookings/health" ] # 
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - micronet
    
  report:
    build: ./report
    container_name: report-svc
    ports:
      - "8085:8085"
    environment:
      # Use Docker service name for inter-service calls
      USER_SERVICE_URL: http://student:8081
    depends_on:
      mysql-db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://localhost:8085/api/reports/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - micronet
    
  library-soap-svc:
    build: ./library_system
    container_name: library-soap-svc
    ports:
      - "8888:8888"
    networks:
      - micronet
    # Optional healthcheck to verify JAX-WS is up and hosting the WSDL metadata
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://localhost:8888/ws/library?wsdl" ]
      interval: 10s
      timeout: 5s
      retries: 3
  
  frontend:
    build: ./frontend
    container_name: frontend-module
    ports:
      - "3000:80"
    networks:
      - micronet

  rabbitmq-server:
    image: rabbitmq:3-management
    container_name: rabbitmq-server
    ports:
      - "5672:5672"   # AMQP protocol port
      - "15672:15672" # Management UI port
    networks:
      - micronet
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  mysql-db:
    image: mysql:latest
    container_name: microservices-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      # Maps init script folder to MySQL's initialization hook
      - ./sqls:/docker-entrypoint-initdb.d
      # Maps the data folder to persistent named volume
      - db-data:/var/lib/mysql
    networks:
      - micronet
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p1234"]
      interval: 10s
      timeout: 5s
      retries: 3

  api-gateway:
    image: nginx:alpine
    container_name: gateway
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      student:
        condition: service_healthy
      enrollment:
        condition: service_healthy
      notification:
        condition: service_healthy
      booking:
        condition: service_healthy
      report:
        condition: service_healthy
      library-soap-svc:
        condition: service_healthy
    networks:
      - micronet

networks:
  micronet:
    driver: bridge

volumes:
  db-data:
