events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    server {
        listen 80;

        # Point Nginx to Docker's internal DNS resolver (Mandatory for dynamic variables)
        resolver 127.0.0.11 valid=5s;

        # Route /api/students to student (Port 8081)
        location /api/students {
            set $student_profile_backend http://student-svc:8081;
            proxy_pass $student_profile_backend;
            
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        # Route /api/enrollments to enrollment (Port 8082)
        location /api/enrollments {
            set $enrollment_backend http://enrollment-svc:8082;
            proxy_pass $enrollment_backend;
            
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Route /api/courses to the same enrollment backend (Port 8082)
        location /api/courses {
            set $enrollment_backend http://enrollment-svc:8082;
            proxy_pass $enrollment_backend;
            
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Route /api/notifications to notification (Port 8083)
        location /api/notifications {
            set $notification_backend http://notification-svc:8083;
            proxy_pass $notification_backend;
            
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Route /api/bookings to booking (Port 8084)
        location /api/bookings {
            set $booking_backend http://booking-api-svc:8084;
            proxy_pass $booking_backend;
            
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Route /api/reports to report (Port 8085)
        location /api/reports {
            set $report_backend http://report-svc:8085;
            proxy_pass $report_backend;
            
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Optional Direct route to Legacy Library SOAP endpoint (Port 8888)
        location /ws/library {
            set $library_backend http://library-soap-svc:8888;
            proxy_pass $library_backend;
            
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        # Gateway health check
        location /health {
            add_header Content-Type application/json;
            return 200 '{"gateway":"UP"}';
        }
    }
}